using Photon.Pun;
using UnityEngine;
using VRSF.Core.Controllers;
using VRSF.Core.SetupVR;

namespace VRSF.Multiplayer
{
    /// <summary>
    /// Used to display a different body for the remote and local users
    /// Need to be placed under the COntrollers Transform object from the PlayerPrefab
    /// </summary>
    [RequireComponent(typeof(PhotonView), typeof(ControllerMeshListing))]
    public class VRSFControllersModel : MonoBehaviourPun
    {
        /// <summary>
        /// Attached to this object, contains a list of meshes based on a type of Device
        /// </summary>
        private ControllerMeshListing _controllersMesh;

        /// <summary>
        /// Reference to the controller generated by this script
        /// </summary>
        private GameObject _controllerInstance;

        private bool _waitForAuthoringAndDestroy;

        private void Awake()
        {
            var controllerAuth = GetComponent<ControllerMeshAuthoring>();

            // We don't need a controller authoring if this player isn't the local player
            if (controllerAuth != null && !photonView.IsMine)
            {
                Destroy(controllerAuth);
            }
            else if (photonView.IsMine)
            {
                // This gameobject is not needed if the photonView is mine, so we destroy it once the authoring phase is done
                _waitForAuthoringAndDestroy = true;
                return;
            }

            _controllersMesh = GetComponent<ControllerMeshListing>();
            VRDeviceWasSet.Listeners += CallInstantiation;
        }

        private void Update()
        {
            // This gameobject is not needed if the photonView is mine, so we destroy it once the authoring phase is done
            if (_waitForAuthoringAndDestroy && GetComponent<ControllerMeshAuthoring>() == null)
                Destroy(gameObject);
        }

        private void OnDestroy()
        {
            if (VRDeviceWasSet.IsMethodAlreadyRegistered(CallInstantiation))
            {
                VRDeviceWasSet.Listeners -= CallInstantiation;
                // Destroy the remote controller
                Destroy(_controllerInstance);
            }
        }

        /// <summary>
        /// Callback for whenever one of the player had sent its device info
        /// Generate the corresponding mesh for the used controllers
        /// </summary>
        /// <param name="info"></param>
        private void CallInstantiation(VRDeviceWasSet info)
        {
            // If the player that has send his info is the one corresponding to this player and the remoteControllers dictionary doesn't contains this player yet
            if (info.Player.NickName == photonView.Owner.NickName)
            {
                if (_controllerInstance != null)
                    Destroy(_controllerInstance);

                // If the other user use the simulator, we do not need to generate a controller
                _controllerInstance = info.Player.DeviceUsed == EDevice.SIMULATOR ? null : GameObject.Instantiate(_controllersMesh.ControllersPerDevice[info.Player.DeviceUsed], transform.parent);
            }
        }
    }
}