// not used but required due to iOS static linkage
void ABGRToI420() {}
void Android420ToI420() {}
void ARGBToI420() {}
void BGRAToI420() {}
void I420Copy() {}
void I420Mirror() {}
void I420Rotate() {}
void I420Scale() {}
void I420ToABGR() {}
void I420ToARGB() {}
void I420ToBGRA() {}
void I420ToRGBA() {}
void RGBAToI420() {}
void speex_echo_cancellation() {}
void speex_echo_capture() {}
void speex_echo_ctl() {}
void speex_echo_playback() {}
void speex_echo_state_destroy() {}
void speex_echo_state_init() {}
void speex_echo_state_init_mc() {}
void speex_echo_state_reset() {}
void speex_preprocess_ctl() {}
void speex_preprocess_run() {}
void speex_preprocess_state_destroy() {}
void speex_preprocess_state_init() {}
void vpx_codec_dec_init_ver() {}
void vpx_codec_decode() {}
void vpx_codec_destroy() {}
void vpx_codec_enc_config_default() {}
void vpx_codec_enc_init_ver() {}
void vpx_codec_encode() {}
void vpx_codec_error() {}
void vpx_codec_error_detail() {}
void vpx_codec_get_cx_data() {}
void vpx_codec_get_frame() {}
void vpx_codec_vp8_cx() {}
void vpx_codec_vp8_dx() {}
void vpx_img_alloc() {}
void vpx_img_free() {}

